# Generated by Django 2.0.13 on 2020-02-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='score',
            field=models.IntegerField(default=5, verbose_name='用户对课程的评分'),
        ),
    ]
