# Generated by Django 2.0.13 on 2020-02-05 11:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190508_2014'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_usercourse_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField(default=5, verbose_name='用户对课程的评分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '课程评分',
                'verbose_name_plural': '课程评分',
            },
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='score',
        ),
    ]
